[pytest]
# Do not set test paths or python paths, let tests discovery do it
# so that both standard and tox mode work fine, without package shadowing

# Directories that are not visited by pytest collector:
norecursedirs = *.egg .eggs dist build docs .tox .git __pycache__

# You will need to measure your tests speed with `-n auto` and without it,
# so you can see whether it gives you any performance gain, or just gives
# you an overhead. See `docs/template/development-process.rst`.
addopts =
  --disable-warnings
  -vl
  --strict
  --tb=auto
  --cov=django_compat_patcher
  --cov-report=html
